"""cor grafico

Revision ID: 000c073e36a1
Revises: de0e5dae42c1
Create Date: 2026-07-30 20:33:33.420681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000c073e36a1'
down_revision: Union[str, Sequence[str], None] = 'de0e5dae42c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codigos', sa.Column('cor', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codigos', 'cor')
    # ### end Alembic commands ###
