"""baseline

Revision ID: 0dee0f194dee
Revises: 
Create Date: 2026-04-22 20:07:02.558756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dee0f194dee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calcoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquia_franquiador_locatario_id', sa.Integer(), nullable=False),
    sa.Column('frota_id', sa.Integer(), nullable=False),
    sa.Column('data_deposito', sa.Date(), nullable=True),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_atual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calcoes_id'), 'calcoes', ['id'], unique=False)
    op.create_table('codigos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('depara_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('obs', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_id'), 'codigos', ['id'], unique=False)
    op.create_table('custos_anuais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frota_id', sa.Integer(), nullable=False),
    sa.Column('custo_id', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('parcela', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custos_anuais_id'), 'custos_anuais', ['id'], unique=False)
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquia_franquiador_locatario_id', sa.Integer(), nullable=False),
    sa.Column('frota_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despesas_id'), 'despesas', ['id'], unique=False)
    op.create_table('despesas_fixas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquia_franquiador_locatario_id', sa.Integer(), nullable=False),
    sa.Column('frota_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despesas_fixas_id'), 'despesas_fixas', ['id'], unique=False)
    op.create_table('faturamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquia_franquiador_locatario_id', sa.Integer(), nullable=False),
    sa.Column('frota_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor_entrada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_saida', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('tipo_pagamento_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faturamentos_id'), 'faturamentos', ['id'], unique=False)
    op.create_table('franqueados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=True),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=30), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=15), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=3), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_franqueados_id'), 'franqueados', ['id'], unique=False)
    op.create_table('franquias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquia', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=30), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_franquias_id'), 'franquias', ['id'], unique=False)
    op.create_table('franquias_fraqueados_locatarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('franquia_id', sa.Integer(), nullable=False),
    sa.Column('franquiado_id', sa.Integer(), nullable=True),
    sa.Column('locatarios_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_franquias_fraqueados_locatarios_id'), 'franquias_fraqueados_locatarios', ['id'], unique=False)
    op.create_table('frotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('renavam', sa.String(length=30), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.Integer(), nullable=True),
    sa.Column('cor', sa.String(length=100), nullable=True),
    sa.Column('fraqueado_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frotas_id'), 'frotas', ['id'], unique=False)
    op.create_table('locatarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=True),
    sa.Column('cnh', sa.String(length=50), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=15), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=3), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_locatarios_id'), 'locatarios', ['id'], unique=False)
    op.create_table('multas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquia_franquiador_locatario_id', sa.Integer(), nullable=False),
    sa.Column('frota_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('data_infracao', sa.Date(), nullable=False),
    sa.Column('data_notificacao', sa.Date(), nullable=False),
    sa.Column('data_indicacao', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_multa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_recebido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pagamento_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multas_id'), 'multas', ['id'], unique=False)
    op.create_table('notas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquiador_id', sa.Integer(), nullable=False),
    sa.Column('frota_id', sa.Integer(), nullable=False),
    sa.Column('valor_bruto_rateado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_liquido_rateado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_id'), 'notas', ['id'], unique=False)
    op.create_table('oficina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquia_franquiador_locatario_id', sa.Integer(), nullable=False),
    sa.Column('frota_id', sa.Integer(), nullable=False),
    sa.Column('data_servico', sa.Date(), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pagamento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('obs', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oficina_id'), 'oficina', ['id'], unique=False)
    op.create_table('planos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plano', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('semanas', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planos_id'), 'planos', ['id'], unique=False)
    op.create_table('semanais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquia_franquiador_locatario_id', sa.Integer(), nullable=False),
    sa.Column('frota_id', sa.Integer(), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semanais_id'), 'semanais', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('tipoAcessoID', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_semanais_id'), table_name='semanais')
    op.drop_table('semanais')
    op.drop_index(op.f('ix_planos_id'), table_name='planos')
    op.drop_table('planos')
    op.drop_index(op.f('ix_oficina_id'), table_name='oficina')
    op.drop_table('oficina')
    op.drop_index(op.f('ix_notas_id'), table_name='notas')
    op.drop_table('notas')
    op.drop_index(op.f('ix_multas_id'), table_name='multas')
    op.drop_table('multas')
    op.drop_index(op.f('ix_locatarios_id'), table_name='locatarios')
    op.drop_table('locatarios')
    op.drop_index(op.f('ix_frotas_id'), table_name='frotas')
    op.drop_table('frotas')
    op.drop_index(op.f('ix_franquias_fraqueados_locatarios_id'), table_name='franquias_fraqueados_locatarios')
    op.drop_table('franquias_fraqueados_locatarios')
    op.drop_index(op.f('ix_franquias_id'), table_name='franquias')
    op.drop_table('franquias')
    op.drop_index(op.f('ix_franqueados_id'), table_name='franqueados')
    op.drop_table('franqueados')
    op.drop_index(op.f('ix_faturamentos_id'), table_name='faturamentos')
    op.drop_table('faturamentos')
    op.drop_index(op.f('ix_despesas_fixas_id'), table_name='despesas_fixas')
    op.drop_table('despesas_fixas')
    op.drop_index(op.f('ix_despesas_id'), table_name='despesas')
    op.drop_table('despesas')
    op.drop_index(op.f('ix_custos_anuais_id'), table_name='custos_anuais')
    op.drop_table('custos_anuais')
    op.drop_index(op.f('ix_codigos_id'), table_name='codigos')
    op.drop_table('codigos')
    op.drop_index(op.f('ix_calcoes_id'), table_name='calcoes')
    op.drop_table('calcoes')
    # ### end Alembic commands ###
