"""criando anexos2

Revision ID: 2aba56cf99c5
Revises: 7fd7ef523411
Create Date: 2026-06-19 14:39:22.816698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2aba56cf99c5'
down_revision: Union[str, Sequence[str], None] = '7fd7ef523411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('franquia_franquiador_locatario_id', sa.Integer(), nullable=False),
    sa.Column('entidade_tipo', sa.String(length=20), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=True),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('arquivo_base64', mysql.LONGTEXT(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anexos_id'), 'anexos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anexos_id'), table_name='anexos')
    op.drop_table('anexos')
    # ### end Alembic commands ###
