"""add campos valor plano, locatarios plano_id, data_inicio_contrato

Revision ID: 2da93961f44a
Revises: 73c8d2724c7b
Create Date: 2026-05-06 12:43:43.258676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2da93961f44a'
down_revision: Union[str, Sequence[str], None] = '73c8d2724c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locatarios', sa.Column('data_inicio_contrato', sa.Date(), nullable=True))
    op.alter_column('locatarios', 'plano_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('planos', sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos', 'valor')
    op.alter_column('locatarios', 'plano_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('locatarios', 'data_inicio_contrato')
    # ### end Alembic commands ###
