"""alter custo

Revision ID: 49905f08e9d5
Revises: 0dee0f194dee
Create Date: 2026-04-22 20:49:49.907132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49905f08e9d5'
down_revision: Union[str, Sequence[str], None] = '0dee0f194dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custos_anuais', sa.Column('custo', sa.String(length=250), nullable=False))
    op.drop_column('custos_anuais', 'custo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custos_anuais', sa.Column('custo_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('custos_anuais', 'custo')
    # ### end Alembic commands ###
