"""add campos valor plano, locatarios plano_id, data_inicio_contrato

Revision ID: 73c8d2724c7b
Revises: e116161a436f
Create Date: 2026-05-06 12:37:53.953840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c8d2724c7b'
down_revision: Union[str, Sequence[str], None] = 'e116161a436f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locatarios', sa.Column('plano_id', sa.Integer(), nullable=False))
    op.add_column('locatarios', sa.Column('data_inicio_contrato', sa.Date(), nullable=False))
    op.add_column('planos', sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos', 'valor')
    op.drop_column('locatarios', 'data_inicio_contrato')
    op.drop_column('locatarios', 'plano_id')
    # ### end Alembic commands ###
