"""criando anexos

Revision ID: 7fd7ef523411
Revises: 9957042a0413
Create Date: 2026-06-19 14:34:49.756732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7fd7ef523411'
down_revision: Union[str, Sequence[str], None] = '9957042a0413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semanais', 'imagem_base64')
    op.drop_column('semanais', 'imagem_tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semanais', sa.Column('imagem_tipo', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('semanais', sa.Column('imagem_base64', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###
