"""gerar log_id

Revision ID: 97fe5f98a957
Revises: 9a52bf7dd898
Create Date: 2026-05-11 17:48:43.672989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fe5f98a957'
down_revision: Union[str, Sequence[str], None] = '9a52bf7dd898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calcoes', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('codigos', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('custos_anuais', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('despesas', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('despesas_fixas', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('faturamentos', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('franqueados', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('franquias', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('franquias_fraqueados_locatarios', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('frotas', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('locatarios', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('multas', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('notas', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('oficina', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('planos', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('semanais', sa.Column('log_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('log_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'log_id')
    op.drop_column('semanais', 'log_id')
    op.drop_column('planos', 'log_id')
    op.drop_column('oficina', 'log_id')
    op.drop_column('notas', 'log_id')
    op.drop_column('multas', 'log_id')
    op.drop_column('locatarios', 'log_id')
    op.drop_column('frotas', 'log_id')
    op.drop_column('franquias_fraqueados_locatarios', 'log_id')
    op.drop_column('franquias', 'log_id')
    op.drop_column('franqueados', 'log_id')
    op.drop_column('faturamentos', 'log_id')
    op.drop_column('despesas_fixas', 'log_id')
    op.drop_column('despesas', 'log_id')
    op.drop_column('custos_anuais', 'log_id')
    op.drop_column('codigos', 'log_id')
    op.drop_column('calcoes', 'log_id')
    # ### end Alembic commands ###
