"""campos para imagens

Revision ID: 9957042a0413
Revises: 97fe5f98a957
Create Date: 2026-06-12 16:28:24.228652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9957042a0413'
down_revision: Union[str, Sequence[str], None] = '97fe5f98a957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semanais', sa.Column('imagem_base64', sa.Text(), nullable=True))
    op.add_column('semanais', sa.Column('imagem_tipo', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semanais', 'imagem_tipo')
    op.drop_column('semanais', 'imagem_base64')
    # ### end Alembic commands ###
