"""alterar tabela despesa

Revision ID: 9a52bf7dd898
Revises: ea333b902c9d
Create Date: 2026-05-08 20:21:27.221020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a52bf7dd898'
down_revision: Union[str, Sequence[str], None] = 'ea333b902c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faturamentos', sa.Column('frota_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faturamentos', 'frota_id')
    # ### end Alembic commands ###
