"""kilometragem

Revision ID: de0e5dae42c1
Revises: eaeea804af80
Create Date: 2026-07-24 14:08:44.422716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0e5dae42c1'
down_revision: Union[str, Sequence[str], None] = 'eaeea804af80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oficina', sa.Column('kilometragem', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oficina', 'kilometragem')
    # ### end Alembic commands ###
