"""campos para imagens google drive

Revision ID: e0f928bd91be
Revises: 2aba56cf99c5
Create Date: 2026-06-22 18:03:36.966318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0f928bd91be'
down_revision: Union[str, Sequence[str], None] = '2aba56cf99c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anexos', sa.Column('drive_file_id', sa.String(length=255), nullable=True))
    op.add_column('anexos', sa.Column('drive_link', sa.String(length=500), nullable=True))
    op.drop_column('anexos', 'arquivo_base64')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anexos', sa.Column('arquivo_base64', mysql.LONGTEXT(), nullable=True))
    op.drop_column('anexos', 'drive_link')
    op.drop_column('anexos', 'drive_file_id')
    # ### end Alembic commands ###
