"""add frota_id locatario

Revision ID: e116161a436f
Revises: 49905f08e9d5
Create Date: 2026-05-04 20:05:10.268090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e116161a436f'
down_revision: Union[str, Sequence[str], None] = '49905f08e9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locatarios', sa.Column('frota_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locatarios', 'frota_id')
    # ### end Alembic commands ###
