"""alterar tabela despesa

Revision ID: ea333b902c9d
Revises: 335e93cd3b44
Create Date: 2026-05-08 14:07:42.240732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea333b902c9d'
down_revision: Union[str, Sequence[str], None] = '335e93cd3b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despesas', sa.Column('mes', sa.Integer(), nullable=False))
    op.add_column('despesas', sa.Column('ano', sa.Integer(), nullable=False))
    op.add_column('despesas', sa.Column('despesa', sa.String(length=100), nullable=False))
    op.drop_column('despesas', 'frota_id')
    op.drop_column('despesas', 'descricao')
    op.drop_column('despesas', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despesas', sa.Column('data', sa.DATE(), nullable=True))
    op.add_column('despesas', sa.Column('descricao', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('despesas', sa.Column('frota_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('despesas', 'despesa')
    op.drop_column('despesas', 'ano')
    op.drop_column('despesas', 'mes')
    # ### end Alembic commands ###
