"""tipo_pagamento

Revision ID: eaeea804af80
Revises: 8aa30295dc8b
Create Date: 2026-07-20 13:47:33.840367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eaeea804af80'
down_revision: Union[str, Sequence[str], None] = '8aa30295dc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faturamentos', sa.Column('tipo_pagamento', sa.String(length=100), nullable=True))
    op.drop_column('faturamentos', 'tipo_pagamento_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faturamentos', sa.Column('tipo_pagamento_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('faturamentos', 'tipo_pagamento')
    # ### end Alembic commands ###
